### ISSUE TITLE
Upgrade to Neo4j 4.1

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqa-neo4j-backend#5]
### Feature Description
 
I, as user
would like to use recent versions of Neo4j
for better experience.

Note that this requires Java 11 as runtime.

### Definition of Done for the Implementers

- [ ] We got a final feedback from the reporting user (_if applicable_)
- [ ] Unittests have been written (_if applicable_)
- [ ] Integration tests have been written (_if applicable_)
- [ ] Test coverage is the same or even better then before (_if applicable_)
- [ ] Documentation has been written (_if applicable_)
- [ ] Added a note on the new feature to the release notes (_if applicable_)

**Comment by murdos** [comment]
@DirkMahler : I guess this issue can be closed, since this a been fixed with https://github.com/jQAssistant/jqa-neo4j-backend/pull/8

**Comment by StephanPirnbaum** [comment]
@murdos good point!
